const paragraphs = [
  "Crazy Liberty City, anything goes. Everything's crazy. Weed is illegal. Ain't that a motherfuck...? Feel free to come to Liberty City but weed is illegal.",
  "Weed is illegal. How the fuck can you make a plant illegal? Weed is just a plant. It's just a plant. It just grows like that an it has some effects if set on fire",
  "Aspirin is perfectly legal, but if you take thirteen of them motherfuckers it'll be your last headache. Long as you have been living you ain't never heard of a motherfucker OD on that bitch.",
  "You might have thought that nigga was dead, he ain't, he gon' wake up in 30 minutes, hungry enough to eat up everything in your damn 2house. That's the side effects. Hungry, happy, sleepy.",
  "The fans in Liberty City are crazy. Let me just say something. If you six foot nine, don't walk up on me all aggressive trying to tell me how much you love me. You scaring the shit out of me, nigga.",
  "\"Hey, son... hey, son, welcome to Liberty City son, you... you funny as fuck, son.\" Wait a minute. Lady, I don't let motherfuckers jus' spit on me while they talking, that's just ridiculous.",
  "They got a guy selling CDs. Motherfucker won't even tell you what's on the CD. He done wrote his name in crayon on the CD, just passing it to you.",
  "Why everything gotta move so fast around here anyway? I want to slow down and relax but you can't do that no way cause weed is illegal. Anyway, that's been all my motherfucking time.",
  'Obviously cancer is a very worthy cause, AIDS is a very worthy cause, but I got asked to do a benefit gig recently for sufferers of obesity. What? Sufferers of obesity. I said "You mean fat people?"',
  'Can you imagine Jesus in the Temple, people coming up to him in bandages, going "Jesus my flesh is falling off"? And he goes "I cant stop now - there\'s a fat woman over there on her third pie".',
  "Well, vaccines might've blinded your children, but it turns out, Mother was right after all! Masturbating will make you go blind, at least to your own self-loathing for sixty seconds.",
  "What causes baldness? Don't take this the wrong way, but the explanation may be downstairs. It's bald, and it wants you to be, too. Through a partially scientific study, doctors have determined that an abundance of testosterone causes baldness.",
  "Until the awful moment when old friends or family come to visit. Maybe it's time to- change your identity! Don't let bad memories blow your cover. We'll teach you all the things you need to alienate your family quick.",
  "Someone's breaking into your home. What do you do? Call 911? It takes the police an average of 35 minutes to respond to a 911 call. In that time, a burglar could have his way with your wife, smoke a cigarette, flip her over and go in for seconds.",
  "I've found a way to relax twenty or thirty times a day. I know it's bad for me, but what's more important? Me, or my children? Stress kills millions of people each year, and causes divorces, automobile accidents, and even war.",
  "Grin! It's scientifically formulated by science to help cure the anxiety, depression, and lack of self-confidence that comes with living a new life in the suburbs. It's safe and non-addictive.",
]
